name: build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    container: fedora:34

    steps:
      - uses: actions/checkout@v2

      - run: |
          dnf -y install cmake git ninja-build qt6-*-devel
          cmake -G Ninja .
          ninja
  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          brew install ninja qt
          cmake -G Ninja .
          ninja
